# Create synthetic dataset from Codi

In [1]:
import pandas as pd
from codi import codi

/home/tomadonna/miniconda3/envs/codi/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
synthetic_data = codi(
    csv_path='raw_data/iris.csv',
    test_split=0.2,
    total_epochs_both=10,
    training_batch_size=1024,
    num_samples=500,
)

In [3]:
display(synthetic_data.head())
display(synthetic_data.describe())
display(synthetic_data.shape)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,17.797576,7.700000,3.270942,3.859409,2.360040,Iris-virginica
1,72.707889,5.081789,4.034629,4.027976,1.331373,Iris-versicolor
2,19.042765,5.805595,4.400000,1.412513,0.615430,Iris-setosa
3,132.787905,6.717944,4.351279,5.893523,1.485806,Iris-setosa
4,90.517944,7.672756,3.437985,5.811242,1.138989,Iris-setosa

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  500.000000     500.000000    500.000000     500.000000    500.000000
mean    79.797794       6.313431      3.305432       4.546125      1.334016
std     48.555729       1.101163      0.778705       1.844226      0.780418
min      1.000000       4.307215      2.000002       1.005179      0.102618
25%     34.210783       5.323967      2.600938       2.883363      0.612745
50%     82.292123       6.527477      3.441262       4.951874      1.369495
75%    126.113184       7.360187      4.029221       6.329373      2.072080
max    150.000000       7.700000      4.400000       6.700000      2.500000

(500, 6)

In [4]:
original_data = pd.read_csv("raw_data/iris.csv")
original_data.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000