# Sklearn style

In [5]:
from katebatic.models.tabddpm.scripts.TabDDPMPipeline import TabDDPMPipeline
import pandas as pd

In [6]:
pipeline = TabDDPMPipeline(
    csv_path="/mnt/d/my_katabatic/raw_data/diabetes.csv",
    target_column="Outcome",
    normalization="quantile",
    train_overrides={"steps": 5000, "lr": 1e-3, "batch_size": 1024},
)
pipeline.fit()

synthetic_df = pipeline.sample(num_samples = 5000, batch_size = 1024)

Reading CSV from /mnt/d/my_katabatic/raw_data/diabetes.csv
Dataset shape: (768, 9)
Target column: Outcome
Normalization method: quantile
Auto-detected task_type: 'binclass' (based on 2 unique target values)
Numerical columns (8): ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']
Categorical columns (0): []
Handling missing values...
Target classes: 2 (['0' '1'])
Data splits - Train: 536, Val: 116, Test: 116

Dataset prepared successfully!
Data saved to: katebatic/models/tabddpm/data/diabetes
Task type: binclass
Features: 8 numerical, 0 categorical
Normalization: quantile
Config saved to: katebatic/models/tabddpm/exp/diabetes/ddpm_cb_best/config.toml with normalization=quantile
Could not detect categorical features from info.json: [Errno 2] No such file or directory: 'data/diabetes/info.json'
CatBoost params saved to: katebatic/models/tabddpm/tuned_models/catboost/diabetes_cv.json
Parameters include cat_features: []
[0]
8
{'num_classes': 2, 'is_y_cond': True, 'd_in': 8, 'rtdl_params': {'d_layers': [256, 256], 'dropout': 0.0}}
mlp
Step 500/5000 MLoss: 0.0 GLoss: 0.4266 Sum: 0.4266
Step 1000/5000 MLoss: 0.0 GLoss: 0.4106 Sum: 0.4106
Step 1500/5000 MLoss: 0.0 GLoss: 0.3963 Sum: 0.3963
Step 2000/5000 MLoss: 0.0 GLoss: 0.3853 Sum: 0.3853
Step 2500/5000 MLoss: 0.0 GLoss: 0.3834 Sum: 0.3834
Step 3000/5000 MLoss: 0.0 GLoss: 0.374 Sum: 0.374
Step 3500/5000 MLoss: 0.0 GLoss: 0.3709 Sum: 0.3709
Step 4000/5000 MLoss: 0.0 GLoss: 0.3677 Sum: 0.3677
Step 4500/5000 MLoss: 0.0 GLoss: 0.3596 Sum: 0.3596
Step 5000/5000 MLoss: 0.0 GLoss: 0.3584 Sum: 0.3584
mlp
Sample timestep    0
Sample timestep    0
Sample timestep    0
Sample timestep    0
Sample timestep    0
Discrete cols: [0]
Num shape:  (5000, 8)
Loaded numerical features: shape (5000, 8)
Loaded target: shape (5000,)

Column names from info.json:
  Numerical columns: ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']
  Categorical columns: []
  Target column: Outcome

In [7]:
synthetic_df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,4.004400,118.489377,68.977013,21.075098,74.878032,31.327123,0.480759,33.255305,0.350400
std,3.642833,33.611225,18.734818,16.896631,108.051156,8.730349,0.357231,11.644127,0.477143
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.084000,21.000000,0.000000
25%,1.000000,97.785014,62.837173,0.000000,0.000000,26.939113,0.244783,23.717968,0.000000
50%,3.000000,115.668680,71.341887,23.246012,18.016967,31.559927,0.391681,29.065645,0.000000
75%,6.000000,137.803620,79.342046,31.714113,126.950713,35.972520,0.614265,41.159894,1.000000
max,17.000000,199.000000,122.000000,99.000000,744.000000,67.099998,2.329000,72.000000,1.000000

In [8]:
original_df = pd.read_csv("/mnt/d/my_katabatic/raw_data/diabetes.csv")
original_df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [9]:
metrics = pipeline.evaluate()
print(metrics)

----------------------------------------------------------------------------------------------------
loading synthetic data: katebatic/models/tabddpm/exp/diabetes/ddpm_cb_best
Train size: (5000, 8), Val size (116, 8)
{'seed': 0, 'normalization': None, 'num_nan_policy': None, 'cat_nan_policy': None, 'cat_min_frequency': None, 'cat_encoding': None, 'y_policy': 'default'}
{'bagging_temperature': 1.0,
 'cat_features': [],
 'depth': 6,
 'early_stopping_rounds': 50,
 'iterations': 2000,
 'l2_leaf_reg': 3.0,
 'leaf_estimation_iterations': 1,
 'learning_rate': 0.03,
 'od_pval': 0.001,
 'task_type': 'CPU',
 'thread_count': 4}
----------------------------------------------------------------------------------------------------
0:	learn: 0.7676200	test: 0.7381067	best: 0.7381067 (0)	total: 3.83ms	remaining: 7.66s
100:	learn: 0.8176577	test: 0.7850578	best: 0.8428640 (4)	total: 98.4ms	remaining: 1.85s
200:	learn: 0.8469106	test: 0.7689738	best: 0.8428640 (4)	total: 204ms	remaining: 1.83s
300:	learn: 0.8679633	test: 0.7770159	best: 0.8428640 (4)	total: 281ms	remaining: 1.59s
400:	learn: 0.8838203	test: 0.7850578	best: 0.8428640 (4)	total: 351ms	remaining: 1.4s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 0.8428640325
bestIteration = 4

Shrink model to first 5 iterations.
(5000,)
****************************************************************************************************
[val]
{'acc': 0.8448, 'f1': 0.8262, 'roc_auc': 0.8137}
[test]
{'acc': 0.7759, 'f1': 0.7489, 'roc_auc': 0.8461}
<lib.metrics.MetricsReport object at 0x7f352b2a9e50>

# Full use of all the functions

In [10]:
from katebatic.models.tabddpm.scripts.TabDDPM import *
from katebatic.models.tabddpm.scripts.data_processing import *
from katebatic.models.tabddpm.scripts.analyze_synthetic_data import *

## Process data
Real data saved at: `katebatic/models/tabddpm/data/`

Synthetic data saved at: `katebatic/models/tabddpm/exp/`

Tuned model saved at: `katebatic/models/tabddpm/tuned_models/`

The pipeline can handle NaN values in features but not in target.

In [2]:
df2 = pd.read_csv('/mnt/d/my_katabatic/raw_data/melbourne_house.csv')
df2.isna().sum()

Suburb               0
Rooms                0
Type                 0
Price                0
Method               0
SellerG              0
Distance             1
Postcode             1
Bedroom2          6441
Bathroom          6447
Car               6824
Landsize          9265
BuildingArea     16591
YearBuilt        15163
CouncilArea          3
Lattitude         6254
Longtitude        6254
Regionname           3
Propertycount        3
dtype: int64

In [3]:
# Regression
prep = prepare_dataset_for_tabddpm(
    csv_path='/mnt/d/my_katabatic/raw_data/melbourne_house.csv',
    dataset_name='melbourne_house',
    target_column='Price',
    task_type='auto',
    normalization='quantile'
)

# Classification
# prep = prepare_dataset_for_tabddpm(
#     csv_path='/mnt/d/my_katabatic/raw_data/Buddy.csv',
#     dataset_name='my_dataset',
#     target_column='breed_category',
#     task_type='auto',
#     normalization='quantile'
# )

Reading CSV from /mnt/d/my_katabatic/raw_data/melbourne_house.csv
Dataset shape: (27247, 19)
Target column: Price
Normalization method: quantile
Auto-detected task_type: 'regression' (based on 2871 unique target values)
Numerical columns (11): ['Rooms', 'Distance', 'Postcode', 'Bedroom2', 'Car', 'Landsize', 'BuildingArea', 'YearBuilt', 'Lattitude', 'Longtitude', 'Propertycount']
Categorical columns (7): ['Suburb', 'Type', 'Method', 'SellerG', 'Bathroom', 'CouncilArea', 'Regionname']
Handling missing values...
  Suburb: 345 categories
  Type: 3 categories
  Method: 5 categories
  SellerG: 349 categories
  Bathroom: 11 categories
  CouncilArea: 34 categories
  Regionname: 9 categories
Regression target range: [85000.000, 11200000.000]
Data splits - Train: 19072, Val: 4087, Test: 4088
Converting categorical features to object dtype...
Categorical features converted to object dtype

Dataset prepared successfully!
Data saved to: katebatic/models/tabddpm/data/melbourne_house
Task type: regression
Features: 11 numerical, 7 categorical
Normalization: quantile
Config saved to: katebatic/models/tabddpm/exp/melbourne_house/ddpm_cb_best/config.toml with normalization=quantile
Could not detect categorical features from info.json: [Errno 2] No such file or directory: 'data/melbourne_house/info.json'
CatBoost params saved to: katebatic/models/tabddpm/tuned_models/catboost/melbourne_house_cv.json
Parameters include cat_features: []

In [4]:
print(prep["real_data_path"])
print(prep["exp_parent_dir"])
print(prep["config_path"])

katebatic/models/tabddpm/data/melbourne_house
katebatic/models/tabddpm/exp/melbourne_house/ddpm_cb_best
katebatic/models/tabddpm/exp/melbourne_house/ddpm_cb_best/config.toml

## Training
python katebatic/models/tabddpm/scripts/pipeline.py --config katebatic/models/tabddpm/exp/my_dataset/ddpm_cb_best/config.toml --train --sample --eval

In [5]:
config_path = "katebatic/models/tabddpm/exp/melbourne_house/ddpm_cb_best/config.toml"
# config_path = "katebatic/models/tabddpm/exp/my_dataset/ddpm_cb_best/config.toml"
cfg = load_cfg(config_path)

In [6]:
train_out  = run_train(cfg, main_overrides={"steps": 2000, "lr": 1e-3, "batch_size": 1024})
train_result  = train_out["result"]

[335   3   5 326  11  34   9]
735
{'num_classes': 0, 'is_y_cond': False, 'd_in': 735, 'rtdl_params': {'d_layers': [256, 256], 'dropout': 0.0}}
mlp
Step 500/2000 MLoss: 2.3513 GLoss: 0.9411 Sum: 3.2924
Step 1000/2000 MLoss: 2.0355 GLoss: 0.8326 Sum: 2.8681
Step 1500/2000 MLoss: 1.8403 GLoss: 0.7109 Sum: 2.5512
Step 2000/2000 MLoss: 1.7453 GLoss: 0.6503 Sum: 2.3956

In [7]:
sample_out = run_sample(cfg, sample_overrides={"batch_size": 1024, "num_samples":5000})
sample_result = sample_out["result"]

mlp
Sample timestep    0
Sample timestep    0
Sample timestep    0
Sample timestep    0
Sample timestep    0
Discrete cols: [0, 3, 4]
Num shape:  (5000, 11)

In [8]:
synthetic_df = load_synthetic_data(
    parent_dir=cfg["parent_dir"],
    real_data_path=cfg["real_data_path"]
)
# View the synthetic data
display(synthetic_df.head())
# print(f"\nShape: {synthetic_df.shape}")
# print(f"\nColumn names: {synthetic_df.columns.tolist()}")
# print(f"\nData types:\n{synthetic_df.dtypes}")

Loaded numerical features: shape (5000, 11)
Loaded categorical features: shape (5000, 7)
Loaded target: shape (5000,)

Column names from info.json:
  Numerical columns: ['Rooms', 'Distance', 'Postcode', 'Bedroom2', 'Car', 'Landsize', 'BuildingArea', 'YearBuilt', 'Lattitude', 'Longtitude', 'Propertycount']
  Categorical columns: ['Suburb', 'Type', 'Method', 'SellerG', 'Bathroom', 'CouncilArea', 'Regionname']
  Target column: Price

,Rooms,Distance,Postcode,Bedroom2,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount,Suburb,Type,Method,SellerG,Bathroom,CouncilArea,Regionname,Price
0,1.0,0.0,3978.0,0.0,0.0,76000.0,0.0,1830.0,-37.39946,144.423798,21650.0,254,2,1,111,1,18,5,9000000.0
1,16.0,0.0,3978.0,0.0,0.0,0.0,3558.0,2019.0,-38.18560,144.423798,121.0,254,0,1,111,1,1,5,9000000.0
2,1.0,0.0,3978.0,0.0,0.0,0.0,3558.0,1830.0,-38.18560,145.526352,21650.0,307,0,1,111,1,18,5,9000000.0
3,1.0,0.0,3000.0,0.0,0.0,0.0,0.0,1830.0,-38.18560,144.423798,21650.0,208,2,1,324,1,18,5,9000000.0
4,1.0,0.0,3000.0,0.0,0.0,0.0,0.0,1830.0,-37.39946,144.423798,21650.0,86,2,1,324,1,18,5,9000000.0

In [9]:
original_df = pd.read_csv('/mnt/d/my_katabatic/raw_data/melbourne_house.csv')
# original_df = pd.read_csv('/mnt/d/my_katabatic/raw_data/Buddy.csv')
original_df.head()

,Suburb,Rooms,Type,Price,Method,SellerG,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,2,h,1480000,S,Biggin,2.5,3067.0,2.0,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,2,h,1035000,S,Biggin,2.5,3067.0,2.0,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,3,h,1465000,SP,Biggin,2.5,3067.0,3.0,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,3,h,850000,PI,Biggin,2.5,3067.0,3.0,2.0,1.0,94.0,NaN,NaN,Yarra City Council,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,4,h,1600000,VB,Nelson,2.5,3067.0,3.0,1.0,2.0,120.0,142.0,2014.0,Yarra City Council,-37.8072,144.9941,Northern Metropolitan,4019.0

In [10]:
eval_out   = run_eval(cfg)
eval_result = eval_out["result"]

----------------------------------------------------------------------------------------------------
loading synthetic data: katebatic/models/tabddpm/exp/melbourne_house/ddpm_cb_best
Train size: (5000, 18), Val size (4087, 18)
{'seed': 0, 'normalization': None, 'num_nan_policy': None, 'cat_nan_policy': None, 'cat_min_frequency': None, 'cat_encoding': None, 'y_policy': 'default'}
{'bagging_temperature': 1.0,
 'cat_features': [],
 'depth': 6,
 'early_stopping_rounds': 50,
 'iterations': 2000,
 'l2_leaf_reg': 3.0,
 'leaf_estimation_iterations': 1,
 'learning_rate': 0.03,
 'od_pval': 0.001,
 'task_type': 'CPU',
 'thread_count': 4}
----------------------------------------------------------------------------------------------------
0:	learn: 0.9895277	test: 3.4491715	best: 3.4491715 (0)	total: 46.5ms	remaining: 1m 32s
100:	learn: 0.7143130	test: 2.7179507	best: 2.7179507 (100)	total: 97.7ms	remaining: 1.84s
200:	learn: 0.6598762	test: 2.5540932	best: 2.5540932 (200)	total: 148ms	remaining: 1.33s
300:	learn: 0.6285241	test: 2.4109162	best: 2.4109162 (300)	total: 197ms	remaining: 1.11s
400:	learn: 0.6069344	test: 2.2606763	best: 2.2605724 (399)	total: 246ms	remaining: 981ms
500:	learn: 0.5869840	test: 2.1919987	best: 2.1913764 (497)	total: 295ms	remaining: 883ms
600:	learn: 0.5726273	test: 2.1309315	best: 2.1297650 (595)	total: 344ms	remaining: 801ms
700:	learn: 0.5581088	test: 2.1162571	best: 2.1162571 (700)	total: 395ms	remaining: 732ms
800:	learn: 0.5479403	test: 2.1079287	best: 2.1036871 (758)	total: 446ms	remaining: 668ms
900:	learn: 0.5381462	test: 2.1090900	best: 2.1036871 (758)	total: 496ms	remaining: 605ms
1000:	learn: 0.5297431	test: 2.0864287	best: 2.0851638 (999)	total: 545ms	remaining: 544ms
1100:	learn: 0.5235739	test: 2.0485077	best: 2.0485077 (1100)	total: 599ms	remaining: 489ms
1200:	learn: 0.5160366	test: 2.0146241	best: 2.0135664 (1190)	total: 649ms	remaining: 432ms
1300:	learn: 0.5085288	test: 2.0127656	best: 2.0088546 (1210)	total: 701ms	remaining: 377ms
1400:	learn: 0.5026667	test: 2.0099600	best: 2.0082614 (1361)	total: 753ms	remaining: 322ms
1500:	learn: 0.4973371	test: 1.9937353	best: 1.9937353 (1500)	total: 801ms	remaining: 266ms
1600:	learn: 0.4919387	test: 1.9918999	best: 1.9889713 (1526)	total: 856ms	remaining: 213ms
1700:	learn: 0.4870463	test: 1.9963486	best: 1.9889713 (1526)	total: 911ms	remaining: 160ms
1800:	learn: 0.4824787	test: 1.9992508	best: 1.9889713 (1526)	total: 960ms	remaining: 106ms
1900:	learn: 0.4782693	test: 1.9781459	best: 1.9780174 (1899)	total: 1.01s	remaining: 52.5ms
1999:	learn: 0.4740808	test: 1.9557251	best: 1.9557251 (1999)	total: 1.05s	remaining: 0us

bestTest = 1.955725111
bestIteration = 1999

(5000,)
****************************************************************************************************
[val]
{'r2': -44.0452, 'rmse': 4217258.8063}
[test]
{'r2': -41.0651, 'rmse': 4212940.693}