In [1]:
# example_usage.py
import pandas as pd
from katebatic.models.TabDDPM import tabddpm

# from sklearn.linear_model import LinearRegression

c:\Users\rjtdu\anaconda3\envs\td\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
import os
os.getcwd()

'c:\\Users\\rjtdu\\OneDrive\\Desktop\\Meeting\\Katebatic'

In [4]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
abalone = fetch_ucirepo(id=1) 
  
# data (as pandas dataframes) 
X = abalone.data.features 
y = abalone.data.targets 

df = pd.concat([X,y], axis=1)

In [5]:
X

,Sex,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550
...,...,...,...,...,...,...,...,...
4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950

In [6]:
X.drop(["Sex"], axis=1, inplace=True)

C:\Users\rjtdu\AppData\Local\Temp\ipykernel_80696\1103020962.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.drop(["Sex"], axis=1, inplace=True)

In [7]:
X

,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight
0,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500
1,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700
2,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100
3,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550
4,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550
...,...,...,...,...,...,...,...
4172,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490
4173,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605
4174,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080
4175,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960
4176,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950

In [9]:
# example_usage.py

# Initialize and train
model = tabddpm.TabDDPM(
    steps=1000,
    lr=0.001,
    weight_decay=1e-5,
    batch_size=4096, 
    model_type='mlp', 
    d_layers=[256, 256],
    dropout=0.0,
    num_classes=0,
    is_y_cond=False,
    normalization='quantile',
    device='cpu',
    seed=1
)

model.fit(X, y)

# Generate synthetic data
# X_syn, y_syn = model.generate(n_samples=100)
synthetic_df = model.generate_df(n_samples=150)

print(synthetic_df.head())

[0]
8
{'is_y_cond': False, 'num_classes': 0, 'rtdl_params': {'d_layers': [256, 256], 'dropout': 0.0}, 'd_in': 8}
mlp
Step 500/1000 MLoss: 0.0 GLoss: 0.266 Sum: 0.266
Step 1000/1000 MLoss: 0.0 GLoss: 0.2577 Sum: 0.2577
mlp
Sample timestep    0
Discrete cols: []
Num shape:  (150, 7)
     Length  Diameter    Height  Whole_weight  Shucked_weight  Viscera_weight  \
0  0.526060  0.430000  0.145000      0.846130        0.306714        0.193051
1  0.633290  0.520000  0.205000      1.966379        0.928322        0.414956
2  0.641281  0.485000  0.158204      1.156270        0.536503        0.309378
3  0.630000  0.519755  0.145000      1.138174        0.480087        0.246309
4  0.469172  0.381769  0.140000      0.503074        0.226266        0.099691

   Shell_weight     target
0      0.251260  13.000000
1      0.517963  10.000000
2      0.321145  11.000000
3      0.376346  15.684479
4      0.120125  11.000000

In [10]:
synthetic_df

,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight,target
0,0.526060,0.430000,0.145000,0.846130,0.306714,0.193051,0.251260,13.000000
1,0.633290,0.520000,0.205000,1.966379,0.928322,0.414956,0.517963,10.000000
2,0.641281,0.485000,0.158204,1.156270,0.536503,0.309378,0.321145,11.000000
3,0.630000,0.519755,0.145000,1.138174,0.480087,0.246309,0.376346,15.684479
4,0.469172,0.381769,0.140000,0.503074,0.226266,0.099691,0.120125,11.000000
...,...,...,...,...,...,...,...,...
145,0.460739,0.345000,0.125000,0.541552,0.219900,0.118869,0.172363,9.000000
146,0.374136,0.265000,0.090323,0.218471,0.099643,0.044496,0.076389,6.571598
147,0.431875,0.325319,0.116350,0.430291,0.169109,0.055821,0.143384,6.000000
148,0.585356,0.475000,0.190000,1.007464,0.423746,0.256003,0.331508,12.000000
149,0.610000,0.465000,0.160000,1.146790,0.593577,0.254754,0.271783,8.000000

In [11]:
df.describe()

,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight,Rings
count,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000
mean,0.523992,0.407881,0.139516,0.828742,0.359367,0.180594,0.238831,9.933684
std,0.120093,0.099240,0.041827,0.490389,0.221963,0.109614,0.139203,3.224169
min,0.075000,0.055000,0.000000,0.002000,0.001000,0.000500,0.001500,1.000000
25%,0.450000,0.350000,0.115000,0.441500,0.186000,0.093500,0.130000,8.000000
50%,0.545000,0.425000,0.140000,0.799500,0.336000,0.171000,0.234000,9.000000
75%,0.615000,0.480000,0.165000,1.153000,0.502000,0.253000,0.329000,11.000000
max,0.815000,0.650000,1.130000,2.825500,1.488000,0.760000,1.005000,29.000000

In [12]:
synthetic_df.describe()

,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight,target
count,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000
mean,0.495746,0.387425,0.142126,0.807621,0.359713,0.177060,0.233952,9.266788
std,0.175194,0.141311,0.127367,0.564818,0.272374,0.133310,0.168150,4.434754
min,0.075000,0.055000,0.000000,0.002000,0.001000,0.000500,0.001500,1.000000
25%,0.429806,0.321283,0.101250,0.358919,0.149437,0.079804,0.110153,8.000000
50%,0.560947,0.433706,0.148638,0.819511,0.353981,0.172863,0.234656,9.000000
75%,0.615000,0.483750,0.165000,1.153900,0.493541,0.246290,0.322836,11.000000
max,0.815000,0.650000,1.130000,2.825500,1.488000,0.760000,1.005000,28.545106

In [13]:
model.clear_cache()

Deleted model directory: exp/temp_798842024

# TSTR - For Classification

In [ ]:
import pandas
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X, y)

In [ ]:
X_syn = synthetic_df.drop(["target"], axis=1)
y_syn = synthetic_df['target']

In [ ]:
predictions = model.predict(X_syn)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [ ]:
cf = confusion_matrix(y_syn, predictions)
print(cf)

In [ ]:
accuracy_score(y_syn, predictions)

# TSTR - For Regression

In [14]:
import pandas
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X, y)

LinearRegression()

In [15]:
X_syn = synthetic_df.drop(["target"], axis=1)
y_syn = synthetic_df['target']

In [16]:
predictions = model.predict(X_syn)

In [17]:
from sklearn.metrics import r2_score

print("The r2 score values is", r2_score(y_syn, predictions))

The r2 score values is 0.7038308872490081