In [ ]:
# example_usage.py
import pandas as pd
from tabddpm import TabDDPM

In [2]:
import os
os.getcwd()

'c:\\Users\\rjtdu\\OneDrive\\Desktop\\TabDDPM\\tddpm'

In [3]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
abalone = fetch_ucirepo(id=1) 
  
# data (as pandas dataframes) 
X = abalone.data.features 
y = abalone.data.targets 

df = pd.concat([X,y], axis=1)

In [4]:
X.drop(["Sex"], axis=1, inplace=True)

c:\Users\rjtdu\anaconda3\envs\tddpm\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [5]:
X

,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight
0,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500
1,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700
2,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100
3,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550
4,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550
...,...,...,...,...,...,...,...
4172,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490
4173,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605
4174,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080
4175,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960
4176,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950

In [6]:
# example_usage.py

import pandas as pd
from tabddpm_wrapper import TabDDPM


# Initialize and train
model = TabDDPM(
    steps=1000,
    lr=0.001,
    weight_decay=1e-5,
    batch_size=4096,
    model_type='mlp',
    d_layers=[256, 256],
    dropout=0.0,
    num_classes=0,
    is_y_cond=False,
    normalization='quantile',
    device='cuda:0',
    seed=0
)

model.fit(X, y)

# Generate synthetic data
# X_syn, y_syn = model.generate(n_samples=100)
synthetic_df = model.generate_df(n_samples=100)

print(synthetic_df.head())

[0]
8
{'is_y_cond': False, 'num_classes': 0, 'rtdl_params': {'d_layers': [256, 256], 'dropout': 0.0}, 'd_in': 8}
mlp
Step 500/1000 MLoss: 0.0 GLoss: 0.2651 Sum: 0.2651
Step 1000/1000 MLoss: 0.0 GLoss: 0.2588 Sum: 0.2588
mlp
Sample timestep    0
Discrete cols: []
Num shape:  (100, 7)
     Length  Diameter  Height  Whole_weight  Shucked_weight  Viscera_weight  \
0  0.354932  0.265000   0.090      0.200539        0.076491        0.052772
1  0.605000  0.468986   0.175      0.997185        0.456335        0.150550
2  0.550000  0.450000   0.150      0.833821        0.327798        0.187300
3  0.394608  0.294144   0.105      0.224616        0.104712        0.051935
4  0.472455  0.345000   0.110      0.475075        0.276261        0.075774

   Shell_weight     target
0      0.069611   7.000000
1      0.309997  10.000000
2      0.271128  12.000000
3      0.088023   7.000000
4      0.119898   6.372752

In [7]:
df.describe()

,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight,Rings
count,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000
mean,0.523992,0.407881,0.139516,0.828742,0.359367,0.180594,0.238831,9.933684
std,0.120093,0.099240,0.041827,0.490389,0.221963,0.109614,0.139203,3.224169
min,0.075000,0.055000,0.000000,0.002000,0.001000,0.000500,0.001500,1.000000
25%,0.450000,0.350000,0.115000,0.441500,0.186000,0.093500,0.130000,8.000000
50%,0.545000,0.425000,0.140000,0.799500,0.336000,0.171000,0.234000,9.000000
75%,0.615000,0.480000,0.165000,1.153000,0.502000,0.253000,0.329000,11.000000
max,0.815000,0.650000,1.130000,2.825500,1.488000,0.760000,1.005000,29.000000

In [8]:
synthetic_df.describe()

,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight,target
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,0.500093,0.390258,0.210535,0.889998,0.417964,0.207729,0.274359,10.166644
std,0.195531,0.158249,0.295217,0.785814,0.402253,0.208851,0.269781,6.247469
min,0.075000,0.055000,0.000000,0.002000,0.001000,0.000500,0.001500,1.000000
25%,0.414236,0.305335,0.098319,0.351503,0.146722,0.063310,0.111010,7.000000
50%,0.530000,0.415000,0.139962,0.765104,0.351459,0.161367,0.234823,9.000000
75%,0.615000,0.481193,0.159423,1.081766,0.483841,0.237113,0.303139,11.000000
max,0.815000,0.650000,1.130000,2.825500,1.488000,0.760000,1.005000,29.000000

In [9]:
model.clear_cache()

Deleted model directory: exp/temp_928994228