The pipeline does not support data preprocessing. All csv file needs to be cleaned, no NaN values before fitting.

In [1]:
from original_pategans import PateGans
import pandas as pd

2025-09-15 03:44:52.509661: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-09-15 03:44:52.518675: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1757871892.528037  169919 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1757871892.530840  169919 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1757871892.538420  169919 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1757871892.538432  169919 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1757871892.538434  169919 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1757871892.538435  169919 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-09-15 03:44:52.541368: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

WARNING:tensorflow:From /home/tomadonna/miniconda3/envs/katebatic/lib/python3.11/site-packages/tensorflow/python/compat/v2_compat.py:98: disable_resource_variables (from tensorflow.python.ops.resource_variables_toggle) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term

In [2]:
pategans = PateGans(
    epsilon=5.0,     
    num_teachers=5      
)

synthetic_data = pategans.fit_generate("raw_data/iris.csv", n_samples=500)
display("Synthetic data shape:", synthetic_data.shape)
display(synthetic_data.describe())

Training on dataset with shape: (150, 6)
Columns: ['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'Species']
Encoding categorical column: Species
Preprocessed data shape: (150, 6)
Data types after preprocessing: [dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64')]
Initializing PATE-GAN...

W0000 00:00:1757871894.344506  169919 gpu_device.cc:2341] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1757871894.512306  169919 mlir_graph_optimization_pass.cc:425] MLIR V1 optimization pass is not enabled

Training PATE-GAN...

Training completed!
Generating 500 synthetic samples...
Generation completed!

'Synthetic data shape:'

(500, 6)

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  500.000000     500.000000    500.000000     500.000000    500.000000
mean    78.552000       5.834749      3.179106       3.756640      1.212725
std     57.230709       1.223138      0.098481       2.569465      1.009812
min     15.000000       4.548620      2.995592       1.114491      0.159633
25%     17.000000       4.594171      3.107107       1.147417      0.177418
50%     67.000000       5.282097      3.202657       2.449524      0.753430
75%    141.000000       7.217311      3.268165       6.654987      2.350029
max    142.000000       7.444917      3.284473       6.746306      2.406935

In [3]:
original_data = pd.read_csv("raw_data/iris.csv")
original_data.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000