The pipeline does not support data preprocessing. All csv file needs to be cleaned, no NaN values before fitting.

In [1]:
from original_pategans import *

2025-09-09 22:24:59.750123: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-09-09 22:24:59.765409: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1757420699.780263   46797 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1757420699.785230   46797 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1757420699.798278   46797 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1757420699.798376   46797 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1757420699.798377   46797 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1757420699.798378   46797 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-09-09 22:24:59.802792: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

WARNING:tensorflow:From /home/tomadonna/miniconda3/envs/katebatic/lib/python3.11/site-packages/tensorflow/python/compat/v2_compat.py:98: disable_resource_variables (from tensorflow.python.ops.resource_variables_toggle) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term

In [ ]:
pategans = PateGans(
    epsilon=5.0,     
    num_teachers=5      
)

synthetic_data = pategans.fit_generate("/mnt/d/Katebatic/raw_data/Buddy_cleaned.csv", n_samples=500)
synthetic_data.to_csv("synthetic_output.csv", index=False)
display("Synthetic data shape:", synthetic_data.shape)
display(synthetic_data.describe())

Training on dataset with shape: (18832, 8)
Columns: ['condition', 'color_type', 'length_m', 'height_cm', 'x1', 'x2', 'breed_category', 'pet_category']
Encoding categorical column: color_type
Preprocessed data shape: (18832, 8)
Data types after preprocessing: [dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64')]
Initializing PATE-GAN...

W0000 00:00:1757420702.219568   46797 gpu_device.cc:2341] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...

Training PATE-GAN...

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1757420702.425003   46797 mlir_graph_optimization_pass.cc:425] MLIR V1 optimization pass is not enabled

Training completed!
Generating 500 synthetic samples...
Generation completed!

'Synthetic data shape:'

(500, 8)

,condition,length_m,height_cm,x1,x2,breed_category,pet_category
count,500.000000,500.000000,500.000000,500.00000,500.000000,500.000000,500.000000
mean,0.738958,0.555399,28.253027,5.36000,3.946000,0.584000,1.768000
std,0.468743,0.126494,7.858075,6.38121,2.940813,0.740297,0.422532
min,0.271023,0.247083,16.106330,0.00000,1.000000,0.000000,1.000000
25%,0.339890,0.494978,23.493881,1.00000,1.000000,0.000000,2.000000
50%,0.505637,0.609785,24.897272,1.00000,3.000000,0.000000,2.000000
75%,1.153804,0.649454,32.498331,12.00000,7.000000,1.000000,2.000000
max,1.684257,0.681259,45.286377,17.00000,9.000000,2.000000,2.000000

In [4]:
original_data = pd.read_csv("/mnt/d/Katebatic/raw_data/Buddy_cleaned.csv")
original_data.describe()

,condition,length_m,height_cm,x1,x2,breed_category,pet_category
count,18832.000000,18832.000000,18832.000000,18832.000000,18832.000000,18832.000000,18832.000000
mean,0.892523,0.502634,27.447901,5.370168,4.577687,0.600627,1.709165
std,0.740309,0.288704,13.019404,6.572482,3.517757,0.629886,0.717936
min,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.250000,16.170000,0.000000,1.000000,0.000000,1.000000
50%,1.000000,0.500000,27.340000,0.000000,4.000000,1.000000,2.000000
75%,1.000000,0.760000,38.890000,13.000000,9.000000,1.000000,2.000000
max,2.000000,1.000000,50.000000,19.000000,9.000000,2.000000,4.000000